In [1]:
pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.3.tar.gz (317.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.3/317.3 MB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.3-py2.py3-none-any.whl size=317840625 sha256=bf109159b5df49b2f47100d1c216c6ab555916cd2f4725dd9a3851acae4f017d
  Stored in directory: /root/.cache/pip/wheels/1b/3a/92/28b93e2fbfdbb07509ca4d6f50c5e407f48dce4ddbda69a4ab
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.3

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [3]:
dataset = [("Bob", 42, 'IT', 2000),
           ("Lisa", 59,  'Finance', 3000),
           ("Diane", 20,  'IT', 5000),
           ("Janet", 60,  'Finance', 7000),
           ("Calvin", 26, 'IT', 4000),
           ("Elena", 24,  'Finance', 6000),
           ("Bill", 50,  'IT', 1000),
           ("Dawn", 33,  'Finance', 8000),
            ("Ken", 66,  'IT',4500),
           ("Lee", 21, 'Finance',6500),
           ("Asha", 53, 'IT',1500),
          ("Marsh", 34,'Finance', 8500)]

col = ['first_name', 'age', 'deptartment', 'salary']

employeedf = spark.createDataFrame(data = dataset,schema = col)

In [4]:
employeedf.show()

+----------+---+-----------+------+
|first_name|age|deptartment|salary|
+----------+---+-----------+------+
|       Bob| 42|         IT|  2000|
|      Lisa| 59|    Finance|  3000|
|     Diane| 20|         IT|  5000|
|     Janet| 60|    Finance|  7000|
|    Calvin| 26|         IT|  4000|
|     Elena| 24|    Finance|  6000|
|      Bill| 50|         IT|  1000|
|      Dawn| 33|    Finance|  8000|
|       Ken| 66|         IT|  4500|
|       Lee| 21|    Finance|  6500|
|      Asha| 53|         IT|  1500|
|     Marsh| 34|    Finance|  8500|
+----------+---+-----------+------+

In [7]:
employeedf.write.option("header",True) \
        .partitionBy("deptartment") \
        .mode("overwrite") \
        .csv("employee")

In [16]:
emp = [("Bob", 42, 'Sales', 2000),
           ("Lisa", 59,  'Finance', 3000),
           ("Diane", 20,  'IT', 5000),
           ("Janet", 60,  'Finance', 7000),
           ("Calvin", 26, 'IT', 4000),
           ("Elena", 24,  'Sales', 6000),
           ("Bill", 50,  'IT', 1000),
           ("Dawn", 33,  'Finance', 8000),
            ("Ken", 66,  'IT',4500),
           ("Lee", 21, 'Sales',6500),
           ("Asha", 53, 'IT',1500),
          ("Marsh", 34,'Finance', 8500)]

col = ['first_name', 'age', 'deptartment', 'salary']

empdf = spark.createDataFrame(data = emp, schema = col)

In [13]:
empdf.show()

+----------+---+-----------+------+
|first_name|age|deptartment|salary|
+----------+---+-----------+------+
|       Bob| 42|      Sales|  2000|
|      Lisa| 59|    Finance|  3000|
|     Diane| 20|         IT|  5000|
|     Janet| 60|    Finance|  7000|
|    Calvin| 26|         IT|  4000|
|     Elena| 24|      Sales|  6000|
|      Bill| 50|         IT|  1000|
|      Dawn| 33|    Finance|  8000|
|       Ken| 66|         IT|  4500|
|       Lee| 21|      Sales|  6500|
|      Asha| 53|         IT|  1500|
|     Marsh| 34|    Finance|  8500|
+----------+---+-----------+------+

`coalesce(2)` służy do zapisania DataFrame empdf w formacie CSV z ograniczeniem liczby plików wyjściowych do 2.

In [14]:
empdf.coalesce(2) \
        .write.option("header",True) \
        .mode("overwrite") \
        .csv("emp")

`repartition(2)` pozwala na pełne przetasowanie danych, co oznacza, że Spark dzieli dane na określoną liczbę partycji niezależnie od istniejącej liczby partycji.

In [17]:
empdf.repartition(2) \
        .write.option("header",True) \
        .mode("overwrite") \
        .csv("emp1")